# Python Installation

## Check current Python version

Before you can begin writing Python code, you'll need the Python interpreter that compiles and runs your code, and a code editor with features that can help you write Python code. 

::: {.callout-important}
We will be using Python 3 for this course, so we will check the Python version before we do anything else.
:::

To check, Python 3 installed on my computer, already, follow the instrations for your Operating System:

::: {.panel-tabset}

## Windows

To determine if your Windows computer already has Python 3:

1.  To open the **Command Prompt** app, go to **Start** on the Windows Taskbar.
    
2.  Enter **cmd** in the Windows search box and select the **Command Prompt App** in the **Best match** results.
    
3.  Enter the following command and then press Enter:
    
        python --version
        
    
    or
    
        py --version
        
    
    Note
    
    Running `python --version` or `py --version` may not return a value, or may return an error message stating _'py' is not recognized as an internal or external command, operable program or batch file._ This indicates Python is not installed on your Windows system.
    
    If you see the word `Python` with a set of numbers separated by `.` characters, some version of Python is installed. Here's an example of the output you might see:
    
            Python 3.10.0
        
    

As long as the first number is `3`, you have Python 3 installed on your computer. Even if you don't have the most up-to-date version, you'll be able to follow along in any of the beginner Python modules on Microsoft Learn.

If the first number is `2` or if you received an error message, you'll need to install Python 3. We'll walk you through installation of Python 3 in the next section.


## macOS

To determine if your macOS computer already has Python 3 installed:

1.  Open the Terminal app by pressing Command + Spacebar key combination to search by using Spotlight.
    
2.  In the search box, enter **Terminal**. In the results set select **Terminal app**, and then press Return to start the app.
    
3.  At the command prompt, enter the following command:
    
        python3 --version
        
    
    Note
    
    Running `python3 --version` may return an error message stating _command not found_. This indicates Python 3 is not installed on your iOS system.
    
    You may see the return output contains the word `Python` followed by a set of numbers separated by `.` characters, for example:
    
        Python 3.10.0
        
    

As long as the first number is `3`, you have Python 3 installed on your computer. Even if you don't have the most up-to-date version, you'll be able to follow along in any of the beginner Python modules on Microsoft Learn.

If you received an error message, you'll need to install Python 3. We'll walk through installation of Python 3 in the next section.

## Linux

Python is pre-installed on most Linux distributions (like Ubuntu).

To determine if your Linux computer already has Python 3 installed:

1.  Open a Linux terminal session. The instructions for opening this session depend on your distribution and version of Linux. Check the online documentation for your Linux distribution for instructions on how to open a terminal session.
    
2.  Enter the following command and then press Enter.
    
        python3 --version
        
    
    Note
    
    Running `python3 --version` may return an error message stating _bash: python3: command not found_. This indicates Python 3 is not installed on your Linux system.
    

The output may include the word `Python` with a set of numbers separated by `.` characters, for example:

        Python 3.10.0
    

As long as the first number is `3`, you have Python 3 installed on your computer. Even if you don't have the most up-to-date version, you'll be able to follow along in any of the beginner Python modules on Microsoft Learn.

If you received an error message, you'll need to install Python 3. We'll walk you through installation of Python 3 in the next section.


:::

## Installation of Python 3

::: {.callout-note}
At the time of writing this document, Python 3.11 was the latest version available, so instructions here refer to that version. Install the latest version of Python that is available for your operating system. If you install a different version, the button labels and the filenames may differ slightly from the installation instructions.
:::

::: {.panel-tabset}

## Windows
Install [Python from python.org](https://www.python.org/downloads/). Use the Download Python button that appears first on the page to download the latest version.

::: {.callout-note} 
If you don't have admin access, an additional option for installing Python on Windows is to use the Microsoft Store. The Microsoft Store provides installs of supported Python versions.
::: 


Execute the file that you have downloaded. This program must be run with your computer's administrator privileges, so be prepared to enter your appropriate password if asked. Click on the option:

> Add Python 3.11 to PATH (or its Mac/Linux equivalent)

**Pay close attention to where on your computer Python is installed and write it down.**


## macOS

The system install of Python on macOS is not supported. Instead, a package management system like `Homebrew` is recommended. To install Python using Homebrew on macOS use `brew install python3` at the Terminal prompt.

::: {.callout-note} 
On macOS, make sure the location of your VS Code installation is included in your PATH environment variable.
::: 

## Linux
The built-in Python 3 installation on Linux works well, but to install other Python packages you must install `pip` with `apt` or `dnf` package mangement depending on your Linux versions.

:::